version: "3"

services:
    staging:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: staging-server
        ports:
            - "3001:3000"
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=staging
        networks:
            - app-network
        restart: always

    production:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: production-server
        ports:
            - "3002:3000"
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=production
        networks:
            - app-network
        restart: always

networks:
    app-network:
        driver: bridge
