version: "3"

services:
    staging:
        image: node:14
        container_name: staging-server
        ports:
            - "3001:3000"
        volumes:
            - ./:/app
        working_dir: /app
        command: bash -c "npm ci && npm start"
        environment:
            - NODE_ENV=staging
            - PORT=3000
        networks:
            - app-network
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    production:
        image: node:14
        container_name: production-server
        ports:
            - "3002:3000"
        volumes:
            - ./:/app
        working_dir: /app
        command: bash -c "npm ci && npm start"
        environment:
            - NODE_ENV=production
            - PORT=3000
        networks:
            - app-network
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

networks:
    app-network:
        driver: bridge
