version: "3"

services:
    staging:
        image: node:14
        container_name: staging-server
        ports:
            - "3001:3000"
        volumes:
            - ./:/app
            - /app/node_modules
        working_dir: /app
        command: bash -c "npm install && npm start"
        environment:
            - NODE_ENV=staging
        networks:
            - app-network
        restart: always
        user: "node"

    production:
        image: node:14
        container_name: production-server
        ports:
            - "3002:3000"
        volumes:
            - ./:/app
            - /app/node_modules
        working_dir: /app
        command: bash -c "npm install && npm start"
        environment:
            - NODE_ENV=production
        networks:
            - app-network
        restart: always
        user: "node"

networks:
    app-network:
        driver: bridge
